<?php

namespace DoctrineORMModule\Proxy\__CG__\MSBios\Voting\Resource\Doctrine\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Poll extends \MSBios\Voting\Resource\Doctrine\Entity\Poll implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'MSBios\\Voting\\Resource\\Doctrine\\Entity\\Poll' . "\0" . 'code', '' . "\0" . 'MSBios\\Voting\\Resource\\Doctrine\\Entity\\Poll' . "\0" . 'subject', '' . "\0" . 'MSBios\\Voting\\Resource\\Doctrine\\Entity\\Poll' . "\0" . 'total', '' . "\0" . 'MSBios\\Voting\\Resource\\Doctrine\\Entity\\Poll' . "\0" . 'options', 'origData', 'data', '' . "\0" . 'MSBios\\Voting\\Resource\\Doctrine\\Entity\\Poll' . "\0" . 'createdAt', '' . "\0" . 'MSBios\\Voting\\Resource\\Doctrine\\Entity\\Poll' . "\0" . 'modifiedAt', '' . "\0" . 'MSBios\\Voting\\Resource\\Doctrine\\Entity\\Poll' . "\0" . 'rowStatus'];
        }

        return ['__isInitialized__', '' . "\0" . 'MSBios\\Voting\\Resource\\Doctrine\\Entity\\Poll' . "\0" . 'code', '' . "\0" . 'MSBios\\Voting\\Resource\\Doctrine\\Entity\\Poll' . "\0" . 'subject', '' . "\0" . 'MSBios\\Voting\\Resource\\Doctrine\\Entity\\Poll' . "\0" . 'total', '' . "\0" . 'MSBios\\Voting\\Resource\\Doctrine\\Entity\\Poll' . "\0" . 'options', 'origData', 'data', '' . "\0" . 'MSBios\\Voting\\Resource\\Doctrine\\Entity\\Poll' . "\0" . 'createdAt', '' . "\0" . 'MSBios\\Voting\\Resource\\Doctrine\\Entity\\Poll' . "\0" . 'modifiedAt', '' . "\0" . 'MSBios\\Voting\\Resource\\Doctrine\\Entity\\Poll' . "\0" . 'rowStatus'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Poll $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCode(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode(string $code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubject', []);

        return parent::getSubject();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubject($subject)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubject', [$subject]);

        return parent::setSubject($subject);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotal', []);

        return parent::getTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotal($total)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotal', [$total]);

        return parent::setTotal($total);
    }

    /**
     * {@inheritDoc}
     */
    public function getOptions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOptions', []);

        return parent::getOptions();
    }

    /**
     * {@inheritDoc}
     */
    public function setOptions($options)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOptions', [$options]);

        return parent::setOptions($options);
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function init()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'init', []);

        return parent::init();
    }

    /**
     * {@inheritDoc}
     */
    public function addData(array $arr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addData', [$arr]);

        return parent::addData($arr);
    }

    /**
     * {@inheritDoc}
     */
    public function setData($key, $value = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData', [$key, $value]);

        return parent::setData($key, $value);
    }

    /**
     * {@inheritDoc}
     */
    public function unsetData($key = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'unsetData', [$key]);

        return parent::unsetData($key);
    }

    /**
     * {@inheritDoc}
     */
    public function getData($key = '', $index = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData', [$key, $index]);

        return parent::getData($key, $index);
    }

    /**
     * {@inheritDoc}
     */
    public function hasData($key = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasData', [$key]);

        return parent::hasData($key);
    }

    /**
     * {@inheritDoc}
     */
    public function __toArray(array $array = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toArray', [$array]);

        return parent::__toArray($array);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray(array $array = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', [$array]);

        return parent::toArray($array);
    }

    /**
     * {@inheritDoc}
     */
    public function toXml(array $array = array (
), $rootName = 'item', $addOpenTag = false, $addCdata = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toXml', [$array, $rootName, $addOpenTag, $addCdata]);

        return parent::toXml($array, $rootName, $addOpenTag, $addCdata);
    }

    /**
     * {@inheritDoc}
     */
    public function toJson(array $array = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toJson', [$array]);

        return parent::toJson($array);
    }

    /**
     * {@inheritDoc}
     */
    public function toString($format = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toString', [$format]);

        return parent::toString($format);
    }

    /**
     * {@inheritDoc}
     */
    public function __call($method, $args)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__call', [$method, $args]);

        return parent::__call($method, $args);
    }

    /**
     * {@inheritDoc}
     */
    public function offsetSet($offset, $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetSet', [$offset, $value]);

        return parent::offsetSet($offset, $value);
    }

    /**
     * {@inheritDoc}
     */
    public function offsetExists($offset)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetExists', [$offset]);

        return parent::offsetExists($offset);
    }

    /**
     * {@inheritDoc}
     */
    public function offsetUnset($offset)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetUnset', [$offset]);

        return parent::offsetUnset($offset);
    }

    /**
     * {@inheritDoc}
     */
    public function offsetGet($offset)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'offsetGet', [$offset]);

        return parent::offsetGet($offset);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrigData($key = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrigData', [$key]);

        return parent::getOrigData($key);
    }

    /**
     * {@inheritDoc}
     */
    public function setOrigData($key = NULL, $data = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrigData', [$key, $data]);

        return parent::setOrigData($key, $data);
    }

    /**
     * {@inheritDoc}
     */
    public function hasDataChangedFor($field)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasDataChangedFor', [$field]);

        return parent::hasDataChangedFor($field);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeInterface $createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifiedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifiedAt', []);

        return parent::getModifiedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifiedAt(\DateTimeInterface $modifiedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifiedAt', [$modifiedAt]);

        return parent::setModifiedAt($modifiedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function isRowStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isRowStatus', []);

        return parent::isRowStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setRowStatus($rowStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRowStatus', [$rowStatus]);

        return parent::setRowStatus($rowStatus);
    }

}
